// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VirtoCommerce.ContentModule.Data.Repositories;

#nullable disable

namespace VirtoCommerce.ContentModule.Data.MySql.Migrations
{
    [DbContext(typeof(MenuDbContext))]
    [Migration("20221216161208_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VirtoCommerce.ContentModule.Data.Model.MenuLinkEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("AssociatedObjectId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("AssociatedObjectName")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<string>("AssociatedObjectType")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MenuLinkListId")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OuterId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("MenuLinkListId");

                    b.ToTable("ContentMenuLink", (string)null);
                });

            modelBuilder.Entity("VirtoCommerce.ContentModule.Data.Model.MenuLinkListEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Language")
                        .HasColumnType("longtext");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OuterId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ContentMenuLinkList", (string)null);
                });

            modelBuilder.Entity("VirtoCommerce.ContentModule.Data.Model.MenuLinkEntity", b =>
                {
                    b.HasOne("VirtoCommerce.ContentModule.Data.Model.MenuLinkListEntity", "MenuLinkList")
                        .WithMany("MenuLinks")
                        .HasForeignKey("MenuLinkListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MenuLinkList");
                });

            modelBuilder.Entity("VirtoCommerce.ContentModule.Data.Model.MenuLinkListEntity", b =>
                {
                    b.Navigation("MenuLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
