// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VirtoCommerce.ContentModule.Data.Repositories;

#nullable disable

namespace VirtoCommerce.ContentModule.Data.PostgreSql.Migrations
{
    [DbContext(typeof(MenuDbContext))]
    [Migration("20250514224735_AddMenuAndMenuItems")]
    partial class AddMenuAndMenuItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VirtoCommerce.ContentModule.Data.Model.MenuEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OuterId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContentMenu", (string)null);
                });

            modelBuilder.Entity("VirtoCommerce.ContentModule.Data.Model.MenuItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AssociatedObjectId")
                        .HasColumnType("text");

                    b.Property<string>("AssociatedObjectName")
                        .HasColumnType("text");

                    b.Property<string>("AssociatedObjectType")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MenuId")
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OuterId")
                        .HasColumnType("text");

                    b.Property<string>("ParentMenuItemId")
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("ParentMenuItemId");

                    b.ToTable("ContentMenuItem", (string)null);
                });

            modelBuilder.Entity("VirtoCommerce.ContentModule.Data.Model.MenuLinkEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AssociatedObjectId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AssociatedObjectName")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("AssociatedObjectType")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MenuLinkListId")
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OuterId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("MenuLinkListId");

                    b.ToTable("ContentMenuLink", (string)null);
                });

            modelBuilder.Entity("VirtoCommerce.ContentModule.Data.Model.MenuLinkListEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OuterId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContentMenuLinkList", (string)null);
                });

            modelBuilder.Entity("VirtoCommerce.ContentModule.Data.Model.MenuItemEntity", b =>
                {
                    b.HasOne("VirtoCommerce.ContentModule.Data.Model.MenuEntity", "Menu")
                        .WithMany("Items")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VirtoCommerce.ContentModule.Data.Model.MenuItemEntity", "ParentMenuItem")
                        .WithMany("Items")
                        .HasForeignKey("ParentMenuItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Menu");

                    b.Navigation("ParentMenuItem");
                });

            modelBuilder.Entity("VirtoCommerce.ContentModule.Data.Model.MenuLinkEntity", b =>
                {
                    b.HasOne("VirtoCommerce.ContentModule.Data.Model.MenuLinkListEntity", "MenuLinkList")
                        .WithMany("MenuLinks")
                        .HasForeignKey("MenuLinkListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MenuLinkList");
                });

            modelBuilder.Entity("VirtoCommerce.ContentModule.Data.Model.MenuEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("VirtoCommerce.ContentModule.Data.Model.MenuItemEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("VirtoCommerce.ContentModule.Data.Model.MenuLinkListEntity", b =>
                {
                    b.Navigation("MenuLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
